# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      docker run --rm -dit --name oracle11 -p 1521:1521 -e ORACLE_PASSWORD=P@ssw0rd! gvenzl/oracle-xe:11-slim
      docker logs oracle11 -f
